package com.liu.service;

import java.util.List;

import com.liu.commonUtils.Page;
import com.liu.pojo.Choose;
import com.liu.pojo.ChooseView;

public interface ChooseService {
	public List<Choose> findChooseList(Choose record);
	public Page<ChooseView> findChooseListWhere(Integer page, Integer rows, String studentname, String subjectID,
			String teacherID, String collegeID ,String ischoose);
	public Page <ChooseView> findChooseListWhereID(Integer page, Integer rows, String studentID, String subjectID,
			String teacherID, String collegeID ,String ischoose );
	public Page <ChooseView> findChooseListWhereTeacherID(Integer page, Integer rows, String studentname, String subjectID,
			String teachername, String collegeID ,String ischoose );
	public Integer findChooseListCount(Choose record);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer chooseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatChoose(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatChooseSelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Choose findByPrimaryKey(Integer chooseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Choose record);
}
