package com.liu.service;

import java.util.List;

import com.liu.commonUtils.Page;
import com.liu.pojo.Grade;
import com.liu.pojo.User;

public interface GradeService {
	public List<Grade> findGradeList(Grade record);
	public Integer findGradeListCount(Grade record);
	public Page<Grade> findGradeListPage(Integer page, Integer rows, String gradename);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatGrade(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatGradeSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Grade findByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Grade record);
}
