package com.liu.service;

import java.util.List;

import com.liu.pojo.Student;

public interface StudentService {
	public List<Student> findStudentList(Student record);
	public Integer findStudentListCount(Student record);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatStudent(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatStudentSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Student findByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Student record);
    Student findByUserID(Integer userid);
}
