package com.liu.service;


import java.util.List;

import com.liu.commonUtils.Page;
import com.liu.pojo.Student;
import com.liu.pojo.Subject;
import com.liu.pojo.SubjectView;

public interface SubjectService {
	public Page<SubjectView> findSubjectList(Integer page, Integer rows, 
            String subContext,String subjectName,
            String teacherID,String collegeID);
	public List<Subject> findAllSubjectList(Subject record);
	public Page<SubjectView> findSubjectListByTeacherID(Integer page, Integer rows,String teacherID);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer subjectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatSubject(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatSubjectSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Subject findByPrimaryKey(Integer subjectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjecttable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Subject record);
    
}
