package com.liu.service;

import java.util.List;

import com.liu.commonUtils.Page;
import com.liu.pojo.User;

public interface UserService {
	public List<User> findUserList(User record);
	public Integer findUserListCount(User record);
	public Page<User> findUserListPage(Integer page, Integer rows, String username,  String usertype,String alltimeUserstate);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatUser(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int creatUserSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    User findByPrimaryKey(String userName, String password ,String usertype);
    User findByPrimaryKeyID(Integer userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(User record);
}
