package com.liu.mapping;

import java.util.List;

import com.liu.pojo.Choose;
import com.liu.pojo.College;

public interface ChooseMapper {
	public List<Choose> selectChooseList(Choose record);
	public Integer selectChooseListCount(Choose record);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer chooseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insert(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insertSelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Choose selectByPrimaryKey(Integer chooseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chooseinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Choose record);
}