package com.liu.mapping;

import java.util.List;

import com.liu.pojo.College;
import com.liu.pojo.Subject;


public interface CollegeMapper {
	public List<College> selectCollegeList(College record);
	public Integer selectCollegeListCount(College record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer collegeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    College selectByPrimaryKey(Integer collegeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collegetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(College record);
}