package com.liu.mapping;

import java.util.List;

import com.liu.pojo.Grade;
import com.liu.pojo.Subject;


public interface GradeMapper {
	public List<Grade> selectGradeList(Grade record);
	public Integer selectGradeListCount(Grade record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Grade selectByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradetable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Grade record);
}