package com.liu.mapping;

import java.util.List;

import com.liu.pojo.Student;
import com.liu.pojo.Teacher;

public interface StudentMapper {
	public List<Student> selectStudentList(Student record);
	public Integer selectStudentListCount(Student record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Student selectByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Student record);
    Student selectByUserID(Integer userid);
}