package com.liu.mapping;

import java.util.List;

import com.liu.pojo.Student;
import com.liu.pojo.Teacher;

public interface TeacherMapper {
	public List<Teacher> selectTeacherList(Teacher record);
	public Integer selectTeacherListCount(Teacher record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int deleteByPrimaryKey(Integer teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    Teacher selectByPrimaryKey(Integer teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherinftable
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    int updateByPrimaryKey(Teacher record);
    Teacher selectByUserID(Integer userid);
}