package com.liu.pojo;
import java.io.Serializable;
public class Choose implements Serializable{
	private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.chooseID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer chooseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer collegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.studentID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.subjectID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chooseinftable.isChoose
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Boolean ischoose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.chooseID
     *
     * @return the value of chooseinftable.chooseID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getChooseid() {
        return chooseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.chooseID
     *
     * @param chooseid the value for chooseinftable.chooseID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setChooseid(Integer chooseid) {
        this.chooseid = chooseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.collegeID
     *
     * @return the value of chooseinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.collegeID
     *
     * @param collegeid the value for chooseinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.studentID
     *
     * @return the value of chooseinftable.studentID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.studentID
     *
     * @param studentid the value for chooseinftable.studentID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.teacherID
     *
     * @return the value of chooseinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.teacherID
     *
     * @param teacherid the value for chooseinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.subjectID
     *
     * @return the value of chooseinftable.subjectID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.subjectID
     *
     * @param subjectid the value for chooseinftable.subjectID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chooseinftable.isChoose
     *
     * @return the value of chooseinftable.isChoose
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Boolean getIschoose() {
        return ischoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chooseinftable.isChoose
     *
     * @param ischoose the value for chooseinftable.isChoose
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setIschoose(Boolean ischoose) {
        this.ischoose = ischoose;
    }
}