package com.liu.pojo;
import java.io.Serializable;
public class College  implements Serializable{
	private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collegetable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer collegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collegetable.collegeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String collegename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collegetable.collegeID
     *
     * @return the value of collegetable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collegetable.collegeID
     *
     * @param collegeid the value for collegetable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collegetable.collegeName
     *
     * @return the value of collegetable.collegeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getCollegename() {
        return collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collegetable.collegeName
     *
     * @param collegename the value for collegetable.collegeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setCollegename(String collegename) {
        this.collegename = collegename == null ? null : collegename.trim();
    }
}