package com.liu.pojo;
import java.io.Serializable;
public class Grade  implements Serializable{
	private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradetable.gradeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer gradeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradetable.gradeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String gradename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradetable.gradeID
     *
     * @return the value of gradetable.gradeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradetable.gradeID
     *
     * @param gradeid the value for gradetable.gradeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradetable.gradeName
     *
     * @return the value of gradetable.gradeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradetable.gradeName
     *
     * @param gradename the value for gradetable.gradeName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }
}