package com.liu.pojo;
import java.io.Serializable;
 public class SubjectView  implements Serializable{
	private static final long serialVersionUID = 1L;

	private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjecttable.subjectName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String subjectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjecttable.subContext
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String subcontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjecttable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teachername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjecttable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String collegename;

	public Integer getSubjectid() {
		return subjectid;
	}

	public void setSubjectid(Integer subjectid) {
		this.subjectid = subjectid;
	}

	public String getSubjectname() {
		return subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	public String getSubcontext() {
		return subcontext;
	}

	public void setSubcontext(String subcontext) {
		this.subcontext = subcontext;
	}

	public String getTeachername() {
		return teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	public String getCollegename() {
		return collegename;
	}

	public void setCollegename(String collegename) {
		this.collegename = collegename;
	}

		
}
