package com.liu.pojo;
import java.io.Serializable;
public class Teacher  implements Serializable{
	private static final long serialVersionUID = 1L;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teachername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherSex
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teachersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer collegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherEmail
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teacheremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherTelephone
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teachertelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherField
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teacherfield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.teacherPost
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String teacherpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherinftable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherID
     *
     * @return the value of teacherinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherID
     *
     * @param teacherid the value for teacherinftable.teacherID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherName
     *
     * @return the value of teacherinftable.teacherName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherName
     *
     * @param teachername the value for teacherinftable.teacherName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherSex
     *
     * @return the value of teacherinftable.teacherSex
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeachersex() {
        return teachersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherSex
     *
     * @param teachersex the value for teacherinftable.teacherSex
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeachersex(String teachersex) {
        this.teachersex = teachersex == null ? null : teachersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.collegeID
     *
     * @return the value of teacherinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.collegeID
     *
     * @param collegeid the value for teacherinftable.collegeID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherEmail
     *
     * @return the value of teacherinftable.teacherEmail
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeacheremail() {
        return teacheremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherEmail
     *
     * @param teacheremail the value for teacherinftable.teacherEmail
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeacheremail(String teacheremail) {
        this.teacheremail = teacheremail == null ? null : teacheremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherTelephone
     *
     * @return the value of teacherinftable.teacherTelephone
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeachertelephone() {
        return teachertelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherTelephone
     *
     * @param teachertelephone the value for teacherinftable.teacherTelephone
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeachertelephone(String teachertelephone) {
        this.teachertelephone = teachertelephone == null ? null : teachertelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherField
     *
     * @return the value of teacherinftable.teacherField
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeacherfield() {
        return teacherfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherField
     *
     * @param teacherfield the value for teacherinftable.teacherField
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeacherfield(String teacherfield) {
        this.teacherfield = teacherfield == null ? null : teacherfield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.teacherPost
     *
     * @return the value of teacherinftable.teacherPost
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getTeacherpost() {
        return teacherpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.teacherPost
     *
     * @param teacherpost the value for teacherinftable.teacherPost
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setTeacherpost(String teacherpost) {
        this.teacherpost = teacherpost == null ? null : teacherpost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherinftable.userID
     *
     * @return the value of teacherinftable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherinftable.userID
     *
     * @param userid the value for teacherinftable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}