package com.liu.pojo;
import java.io.Serializable;
public class User   implements Serializable{
	private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertable.userName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertable.password
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertable.userType
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertable.userstate
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    private Byte userstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertable.userID
     *
     * @return the value of usertable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertable.userID
     *
     * @param userid the value for usertable.userID
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertable.userName
     *
     * @return the value of usertable.userName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertable.userName
     *
     * @param username the value for usertable.userName
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertable.password
     *
     * @return the value of usertable.password
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertable.password
     *
     * @param password the value for usertable.password
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertable.userType
     *
     * @return the value of usertable.userType
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertable.userType
     *
     * @param usertype the value for usertable.userType
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertable.userstate
     *
     * @return the value of usertable.userstate
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public Byte getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertable.userstate
     *
     * @param userstate the value for usertable.userstate
     *
     * @mbg.generated Mon Dec 03 17:27:37 CST 2018
     */
    public void setUserstate(Byte userstate) {
        this.userstate = userstate;
    }
}